pipeline {
    agent any
    parameters {
        booleanParam(name: 'RUN_MAVEN', defaultValue: true, description: 'Run Maven build stage')
        booleanParam(name: 'RUN_DOCKER', defaultValue: false, description: 'Run Docker build stage')
    }
    stages {

                stage('mvn clean build')
                {
                        when {
        expression { params.RUN_MAVEN }
    }
                    steps
                    {
                       dir('calculator') {
                            bat 'mvn clean install'
                        }
                    }
                }
                stage('Docker Build & Push') {
                        when {
        expression { params.RUN_DOCKER }
    }
                    steps {
                        script {
                            def version = bat(
                                script: 'cd calculator && mvn help:evaluate -Dexpression=project.version -q -DforceStdout',
                                returnStdout: true
                            ).trim()
                            
                            withCredentials([usernamePassword(credentialsId: 'dockerhub-cred',
                                                            usernameVariable: 'DOCKER_USER',
                                                            passwordVariable: 'DOCKER_PASS')]) {
                                bat """
                                echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                                docker build -t calculator-app:${version} -f calculator/Dockerfile calculator/
                                docker tag calculator-app:${version} calculator-app:latest
                                docker tag calculator-app:${version} %DOCKER_USER%/calculator:${version}
                                docker tag calculator-app:${version} %DOCKER_USER%/calculator:latest
                                docker push %DOCKER_USER%/calculator:${version}
                                docker push %DOCKER_USER%/calculator:latest
                                """
                            }
                        }
                    }
                }
    }
}
