pipeline {
    agent any
    parameters{
        choice(name: 'build_options', choices: ['build', 'docker build & push'], description: 'Select the build option')
    }
    stages {
                stage('mvn clean build')
                {
                    when {
                        expression { params.build.options == 'build'}
                    }
                    steps
                    {
                       dir('calculator') {
                            bat 'mvn clean install'
                        }
                    }
                }
                stage('Docker Build & Push') {
                    when {
                        expression { params.build_options == 'docker build & push'}
                    }
                    steps {
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-cred',
                                                        usernameVariable: 'DOCKER_USER',
                                                        passwordVariable: 'DOCKER_PASS')]) {
                            bat """
                            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                            docker build -t calculator-app:latest -f calculator/Dockerfile calculator/
                            docker tag calculator-app:latest %DOCKER_USER%/calculator-app:latest
                            docker push %DOCKER_USER%/calculator-app:latest
                            """
                        }
                    }
                }
    }
}
