spring.application.name=calculator-app
server.port=8081
server.servlet.context-path=/
spring.web.resources.static-locations=classpath:/static/

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized
