apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment 
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator-container
        image: hrk45/calculator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Xmx512m"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3